[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.128.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 200
